### ISSUE TITLE
CP4I check for operand status fails if other conditions besides Deployed in status

### ISSUE THREAD

**Issue by rich-ehrhardt** [IBM/azure-marketplace-arm-templates#163]
Tested deployment on an OCP v4.17 cluster and got the following status
```
status:
  conditions:
    - lastTransitionTime: '2025-02-26T00:49:38Z'
      message: 'An instance [16.1.0.0] has been installed but the OCP version [4.17.11] does not match the supported environment for this version.'
      reason: OcpSupport
      status: 'True'
      type: Warning
    - lastTransitionTime: '2025-02-26T00:50:12Z'
      message: Platform UI has been provisioned.
      reason: Deployed
      status: 'True'
      type: Ready
```

The UI successfully deployed, but the deployment playbook did not recognise it as it showed `Warning`.
